apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: bank-app
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'bank-app'
        static_configs:
          - targets: ['localhost:9090']
