apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank
  namespace: bank-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
        - name: bank
          image: bank/app:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: bank-app-config
            - secretRef:
                name: postgres-secret
