
apiVersion: v1
kind: Service
metadata:
  name: bank-service
  namespace: bank-app
spec:
  selector:
    app: bank
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
